### ISSUE TITLE
"Other Bonuses" not resolving values

### ISSUE THREAD

**Issue by Darxide23** [AntoineThebaud/swlcalc#8]
Just a small issue, but under "Other Bonuses" it will show "_%d_" for damage or healinginstead of the actual number. I don't know if this is by design or not, just thought I'd report it in case it's unintended. The easiest way to get this is to pick Diviciacus as an agent.

I'm unsure of other non damage/healing values.

Edit: Testing "The Cleaner" shows the 5% knockdown properly as well as the +10% Filth damage. It seems to be flat values that aren't displaying right. Percentage based numbers show just fine.

**Comment by AntoineThebaud** [comment]
Nice catch ! Yes it seems this issue is happening for bonuses that are affected by CP/HP. Btw when you do any other change right after, it gets refreshed and displayed properly. Please use this as a workaround until I patch this.

**Comment by AntoineThebaud** [comment]
Patch released just now that solved this issue. Thanks again for your contribution !
